### ISSUE TITLE
Relation with OpenWrt and upstreaming plans?

### ISSUE THREAD

**Issue by tinxx** [mammo0/openwrt-bpi-r2#1]
Hi @mammo0, thanks for providing actually working images.

Can you please clarify a few points:

1. What changes were actually necessary to make OpenWrt boot on BPI-R2?
2. What is your relationship with the _official_ OpenWrt team?
3. Are you working together with them/are there plans to upstream your changes?

There are [complete images](https://downloads.openwrt.org/snapshots/targets/mediatek/mt7623/openwrt-mediatek-mt7623-bpi_bananapi-r2-squashfs-img.gz) now in the _official_ snapshot branch.  
I also found a [getting started guide](https://forum.openwrt.org/t/getting-started-with-bananapi-bpi-r2/83376) on the forums that uses the _official_ image.  
However, I flashed it onto a SD card and it didn't seem to come up. At least DHCP didn't work and it didnt response to `root@192.168.1.1`, whatsoever.

It would be cool to see this go upstream and allow for official builds to work!

Cheers,
Tinx

**Comment by mammo0** [comment]
Hello @tinxx,

of course I can answer your questions:

1. Please have a look at the official OpenWRT docu/wiki: https://openwrt.org/toh/sinovoip/sinovoip_banana_pi_r2
and this site: https://fw-web.de/dokuwiki/doku.php?id=en:bpi-r2:uboot
This helped me a lot to understand the boot process of the BPi R2.
2. I'm not in any relation to the official OpenWRT team.
3. No and No...
 
I made this Repo because I wanted OpenWRT 19.07.x on my BPi, not the official supported version 18.06.x. Mainly I followed the steps described in the official Wiki mentioned above.
To automate these steps I wrote some scripts and shared them on GH.

A few weeks ago I also noticed that there are now images on the snapshot branch.
If you look into the current master (https://github.com/openwrt/openwrt/tree/master/target/linux/mediatek/image) you see, that there are now more scripts for creating SD card and EMMC images. In comparison same directory on the 19.07 branch: https://github.com/openwrt/openwrt/tree/openwrt-19.07/target/linux/mediatek/image

So I think there is some work done in the background to better support the BPi R2. Maybe those changes will be in the next main version of OpenWRT. If you want more information about this topic, I think the best is to directly contact the OpenWRT team.

To your problem with the snapshot builds:
I don't use the snapshot builds, because according to the official Wiki they're untested and possible unstable (https://openwrt.org/releases/snapshot). But for my usecase I need stable software. So I can't help you to get those images working.

I found also a guide that describes how to build the snapshot images: http://forum.banana-pi.org/t/howto-build-19-07-3-openwrt-image-for-bpi-r2/11503
You may try that one.

**Comment by mammo0** [comment]
Since there are no questions left here, I'll close this now.
