### ISSUE TITLE
Sata hdd not detected

### ISSUE THREAD

**Issue by Potuyt** [mammo0/openwrt-bpi-r2#2]
I have connected a sata hdd to the banana r2 but it won't detect the hard drive as sda in /dev.

**Comment by mammo0** [comment]
Hello,

at first please know that I'm not a member of the OpenWRT team. So I can't provide support for their software. I'm just providing ready to use SD card an EMMC images for the BPi R2. These images use the default configuration from the official OpenWRT builds.

I think you have an issue with the OpenWRT software itself and not anything related to my images. So please contact the OpenWRT team directly through the official channels.

**Or do a short web search:**
Because than you find an entry in the official Wiki which describes how to use external devices with OpenWRT: https://openwrt.org/docs/guide-user/storage/usb-drives

And for (e)SATA devices I found the following guide: https://forum.openwrt.org/t/esata-drive-attaching/73534/2
