### ISSUE TITLE
Only 1 GB RAM with prebuild images

### ISSUE THREAD

**Issue by coldBug** [mammo0/openwrt-bpi-r2#5]
With your images my system has only 1GB RAM available.

When booting there is only the 1GB detected in boot log. I have also built a OpenWRT dev image with Linux kernel 5.4 and have 2GB RAM available with it.

Do you have that same issue as well?

**Comment by mammo0** [comment]
Well, actually I didn't checked that yet...
But I will do that in the next days, because now I don't have access to my R2. Will report back.

**Comment by mammo0** [comment]
I've checked my R2 and you're right, there are only 1GB of RAM available. After some research I think that it has to do with the `dts` file for the R2.

*OpenWRT 19.07 uses kernel 4.14:*
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm/boot/dts/mt7623n-bananapi-bpi-r2.dts?h=v4.14&id=bebc6082da0a9f5d47a1ea2edc099bf671058bd4

*OpenWRT 21.02 uses kernel 5.4:*
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm/boot/dts/mt7623n-bananapi-bpi-r2.dts?h=v5.4&id=219d54332a09e8d8741c1e1982f5eae56099de85

You see that there is also a difference in the memory section. So that might cause it.

I don't know if the `dts` file from the 5.4 kernel will work with the 4.14. Maybe there are downsides. My intention of this Repo is to stick as near as possible to the original OpenWRT release, so I don't think I will change that.
If you need 2GB of memory, you can try to use the 5.4 `dts` file.
